version: '3.4'
services:
  api:
    build: 
        context: .
        dockerfile: ./HackerNews.API.Host/Dockerfile
    
  web:
    build:
        context: ./HackerNews.ReactWebUI
        dockerfile: ./Dockerfile
    tty: true

networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 3.10.0.0/16
          gateway: 3.10.0.1